### PR TITLE
A few unrelated bugfixes

### PR DESCRIPTION
**Pull request by keflavich**
If you want, I can split these up.  The most substantive changes are re: #14.  Others are things I put in to help me track the progress of the code; these could be removed.  There's also an import change (that's a real bugfix) and a change to the packagename in the setup.

### CODE REVIEW

**Comment by andrew-saydjari** [comment]
I will let @schlafly do the review, but there is some problem associated with versioning in conda that has caused issues with the conda-forge feedstock for crowdsource that is causing my CloudCovErr.jl unit tests to fail, so I releasing a new crowdsource package was on my to do list anyway. Happy to handle that part of it.

**Comment by schlafly** [comment]
Thanks for the PR.  Let me review and merge tomorrow.  I may tweak the get_sizes(...) implementation, but it's good to have that configurable now.  I don't understand python packaging well enough; Andrew, can you confirm the change to the name in the setup script?  Thanks!

**Comment by schlafly** [comment]
Can you see if this API for get_sizes(...) fits your needs?  I also took the liberty of adding some line breaks.  I haven't been being careful about print(..., flush=True); if you're having issues there, you might consider starting python in unbuffered mode (python -u), rather than adding to the print messages.

**Comment by keflavich** [comment]
the `flush=True` stuff probably was unnecessary.

I think the API works but I'm not sure I know what `blistsz` is... is `blist` a list of bright stars?

In any case, yeah, I think this adds the flexibility needed.

**Comment by schlafly** [comment]
Yes, in DECaPS / WISE we occasionally observe alpha Cen / whatever and it's possible for hundreds of pixels to be masked.  We try to do a little better in those cases by using the full 299x299 stamp we have.  That's only new in that I moved the hard coded constant into a default parameter.

**Comment by andrew-saydjari** [comment]
@schlafly Looks good to me. I built and tested on TestPyPI and had no issues. I just bumped the patch version number. After you merge, I will issue a Github release, push to PyPi production, after which it should appear on conda-forge same day. My real concern is that I made CloudCovErr.jl depend on crowdsource (a bad idea in retrospect) and I am worried about downstream compatibility issues. So I am fine with going ahead with this as long as you are ok with some possible patch version number incrementing while I troubleshoot that in the next few days.

**Comment by schlafly** [comment]
Great, merging.

**Pull request merged**
